### ISSUE TITLE
Add comment after php-smelly-code-detector summary

### ISSUE THREAD

**Issue by abenevaut** [abenevaut/opensource#282]
- https://github.com/abenevaut/php-smelly-code-detector

```
      - name: Smelly Code Detector
        if: github.event_name == 'pull_request' && matrix.record_coverage
        run: |
          vendor/bin/smelly-code-detector inspect src | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" > tmp.txt
          sed '$d' tmp.txt > tmp2.txt
          sed '$d' tmp2.txt > tmp.txt
          sed '2d' tmp.txt > tmp2.txt
          sed '2d' tmp2.txt > tmp.txt
          sed '2d' tmp.txt > tmp2.txt
          sed 's/+/|/g' tmp2.txt > ../.github/workflows/smelly-code-detector.txt
          rm tmp.txt tmp2.txt

      - uses: actions/upload-artifact@v4
        with:
          name: smelly-code-detector
          path: ${{ github.workspace }}/.github/workflows/smelly-code-detector.txt
          retention-days: 1
          compression-level: 9
          overwrite: true
```

```
  comment:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      # needed by `NejcZdovc/comment-pr` action
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        php_version: [ 83, 84 ]
        include:
          - php_version: 83
            record_coverage: true
          - php_version: 84
            record_coverage: false
    concurrency:
      group: laravel-sentry-handler-comment-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: false
    steps:

      - uses: actions/download-artifact@v4
        if: github.event_name == 'pull_request' && matrix.record_coverage
        with:
          name: smelly-code-detector
          path: ${{ github.workspace }}/.github/workflows

      - uses: NejcZdovc/comment-pr@v2
        if: github.event_name == 'pull_request' && matrix.record_coverage
        with:
          file: smelly-code-detector.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
